
spring.application.name=gestion-comercial

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_comercial
spring.datasource.username=postgres
spring.datasource.password=Geremi2017*

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration