-- ============================================================
-- Trabajo Final TUP - Esquema inicial PostgreSQL
-- Aplicación web para gestión de productos, pedidos y stock
-- Recomendado para Spring Boot + Spring Data JPA/Hibernate
-- ============================================================
--
-- Decisión técnica: los valores de estado/tipo se almacenan como VARCHAR
-- con CHECK constraints. En Java pueden modelarse con enum +
-- @Enumerated(EnumType.STRING), evitando complejidad adicional con los
-- ENUM nativos de PostgreSQL.

BEGIN;

-- ============================================================
-- DATOS GENERALES Y CONFIGURACIÓN
-- ============================================================

CREATE TABLE datos_comercio (
    id_datos_comercio       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                  VARCHAR(100) NOT NULL,
    descripcion             TEXT,
    sobre_nosotros          TEXT,
    telefono                VARCHAR(30),
    correo                  VARCHAR(100),
    direccion               VARCHAR(150),
    localidad               VARCHAR(100),
    provincia               VARCHAR(100),
    logo_url                VARCHAR(255),
    imagen_portada_url      VARCHAR(255)
);

CREATE TABLE configuracion_comercio (
    id_configuracion                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto_minimo_envio              NUMERIC(12,2) NOT NULL DEFAULT 25000.00,
    permite_envio_villa_maria      BOOLEAN NOT NULL DEFAULT TRUE,
    permite_envio_villa_nueva      BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_actualizacion             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_config_monto_envio CHECK (monto_minimo_envio >= 0)
);

-- ============================================================
-- SEGURIDAD Y USUARIOS
-- ============================================================

CREATE TABLE roles (
    id_rol          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(50) NOT NULL,
    descripcion     VARCHAR(150)
);

CREATE UNIQUE INDEX ux_roles_nombre_lower ON roles (LOWER(nombre));

CREATE TABLE usuarios (
    id_usuario      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol          INT NOT NULL REFERENCES roles(id_rol),
    nombre          VARCHAR(100) NOT NULL,
    apellido        VARCHAR(100),
    email           VARCHAR(120) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    estado          VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    fecha_alta      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_usuario_estado CHECK (estado IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO'))
);

-- ============================================================
-- CLIENTES
-- ============================================================

CREATE TABLE clientes (
    id_cliente                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario                  INT UNIQUE REFERENCES usuarios(id_usuario),
    nombre                      VARCHAR(100) NOT NULL,
    apellido                    VARCHAR(100),
    dni                         VARCHAR(20),
    telefono                    VARCHAR(30),
    correo                      VARCHAR(120),
    razon_social                VARCHAR(150),
    cuit                        VARCHAR(20),
    condicion_iva               VARCHAR(80),
    direccion_facturacion       VARCHAR(200),
    localidad_facturacion       VARCHAR(100),
    provincia_facturacion       VARCHAR(100),
    descuento_porcentaje        NUMERIC(5,2),
    nota_interna                TEXT,
    estado                      BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_alta                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_cliente_descuento CHECK (
        descuento_porcentaje IS NULL
        OR (descuento_porcentaje >= 0 AND descuento_porcentaje <= 100)
    )
);

CREATE TABLE direcciones_envio_cliente (
    id_direccion_envio     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente             INT NOT NULL REFERENCES clientes(id_cliente),
    calle                  VARCHAR(100) NOT NULL,
    numero                 VARCHAR(20) NOT NULL,
    piso_departamento      VARCHAR(50),
    localidad              VARCHAR(30) NOT NULL,
    referencia             TEXT,
    CONSTRAINT chk_direccion_localidad CHECK (localidad IN ('VILLA_MARIA', 'VILLA_NUEVA'))
);

-- ============================================================
-- PRODUCTOS Y CATÁLOGO
-- ============================================================

CREATE TABLE categorias (
    id_categoria     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(100) NOT NULL,
    descripcion      TEXT,
    activa           BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX ux_categorias_nombre_lower ON categorias (LOWER(nombre));

CREATE TABLE marcas (
    id_marca         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(100) NOT NULL,
    activa           BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX ux_marcas_nombre_lower ON marcas (LOWER(nombre));

CREATE TABLE grupos_catalogo (
    id_grupo_catalogo    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_visible       VARCHAR(120) NOT NULL,
    descripcion          TEXT,
    activo               BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX ux_grupos_catalogo_nombre_lower ON grupos_catalogo (LOWER(nombre_visible));

CREATE TABLE productos (
    id_producto                         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria                        INT REFERENCES categorias(id_categoria),
    id_marca                            INT REFERENCES marcas(id_marca),
    id_grupo_catalogo                   INT REFERENCES grupos_catalogo(id_grupo_catalogo),
    nombre                              VARCHAR(120) NOT NULL,
    descripcion                         TEXT,
    precio_costo                        NUMERIC(12,2),
    precio_venta                        NUMERIC(12,2) NOT NULL,
    stock_actual                        INT NOT NULL DEFAULT 0,
    stock_minimo                        INT NOT NULL DEFAULT 0,
    cantidad_minima_mayorista           INT,
    porcentaje_descuento_mayorista      NUMERIC(5,2),
    en_oferta                           BOOLEAN NOT NULL DEFAULT FALSE,
    porcentaje_descuento_oferta         NUMERIC(5,2),
    estado                              VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    publicado_online                    BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_alta                          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_producto_precio_costo CHECK (precio_costo IS NULL OR precio_costo >= 0),
    CONSTRAINT chk_producto_precio_venta CHECK (precio_venta > 0),
    CONSTRAINT chk_producto_stock_actual CHECK (stock_actual >= 0),
    CONSTRAINT chk_producto_stock_minimo CHECK (stock_minimo >= 0),
    CONSTRAINT chk_producto_estado CHECK (estado IN ('ACTIVO', 'PAUSADO', 'DISCONTINUADO')),
    CONSTRAINT chk_producto_mayorista CHECK (
        (cantidad_minima_mayorista IS NULL AND porcentaje_descuento_mayorista IS NULL)
        OR
        (cantidad_minima_mayorista > 0
         AND porcentaje_descuento_mayorista > 0
         AND porcentaje_descuento_mayorista <= 100)
    ),
    CONSTRAINT chk_producto_oferta CHECK (
        (en_oferta = FALSE AND porcentaje_descuento_oferta IS NULL)
        OR
        (en_oferta = TRUE
         AND porcentaje_descuento_oferta > 0
         AND porcentaje_descuento_oferta <= 100)
    )
);

CREATE INDEX ix_productos_nombre ON productos(nombre);
CREATE INDEX ix_productos_categoria ON productos(id_categoria);
CREATE INDEX ix_productos_marca ON productos(id_marca);
CREATE INDEX ix_productos_grupo ON productos(id_grupo_catalogo);
CREATE INDEX ix_productos_estado_publicado ON productos(estado, publicado_online);

CREATE TABLE imagenes_producto (
    id_imagen       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto     INT NOT NULL REFERENCES productos(id_producto),
    url_imagen      VARCHAR(255) NOT NULL,
    orden           INT,
    principal       BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_imagen_orden CHECK (orden IS NULL OR orden >= 0)
);

-- Garantiza como máximo una imagen principal por producto.
CREATE UNIQUE INDEX ux_imagen_principal_producto
    ON imagenes_producto(id_producto)
    WHERE principal = TRUE;

CREATE INDEX ix_imagenes_producto ON imagenes_producto(id_producto);

-- ============================================================
-- MEDIOS DE PAGO
-- ============================================================

CREATE TABLE medios_pago (
    id_medio_pago    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(80) NOT NULL,
    activo           BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX ux_medios_pago_nombre_lower ON medios_pago (LOWER(nombre));

-- ============================================================
-- PEDIDOS Y VENTAS
-- ============================================================

CREATE TABLE pedidos (
    id_pedido               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido           VARCHAR(30) NOT NULL UNIQUE,
    id_cliente              INT REFERENCES clientes(id_cliente),
    id_medio_pago           INT NOT NULL REFERENCES medios_pago(id_medio_pago),
    id_direccion_envio      INT REFERENCES direcciones_envio_cliente(id_direccion_envio),
    tipo_venta              VARCHAR(20) NOT NULL,
    estado_pedido           VARCHAR(30) NOT NULL,
    estado_pago             VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    tipo_facturacion        VARCHAR(30),
    medio_entrega           VARCHAR(20) NOT NULL,
    localidad_envio         VARCHAR(30),
    direccion_envio         VARCHAR(200),
    fecha_creacion          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subtotal                NUMERIC(12,2) NOT NULL DEFAULT 0,
    descuento_cliente       NUMERIC(12,2) NOT NULL DEFAULT 0,
    descuento_mayorista     NUMERIC(12,2) NOT NULL DEFAULT 0,
    descuento_oferta        NUMERIC(12,2) NOT NULL DEFAULT 0,
    total                   NUMERIC(12,2) NOT NULL DEFAULT 0,
    descripcion_pago        TEXT,
    observaciones_cliente   TEXT,
    observaciones_internas  TEXT,

    CONSTRAINT chk_pedido_tipo_venta CHECK (tipo_venta IN ('ONLINE', 'LOCAL')),
    CONSTRAINT chk_pedido_estado CHECK (estado_pedido IN (
        'PENDIENTE_APROBACION', 'CONFIRMADO', 'EN_PREPARACION',
        'LISTO_PARA_RETIRAR', 'LISTO_PARA_ENVIAR', 'ENVIADO',
        'ENTREGADO', 'CANCELADO'
    )),
    CONSTRAINT chk_pedido_pago CHECK (estado_pago IN ('PENDIENTE', 'PAGADO')),
    CONSTRAINT chk_pedido_facturacion CHECK (
        tipo_facturacion IS NULL OR tipo_facturacion IN (
            'CONSUMIDOR_FINAL', 'FACTURA_A', 'FACTURA_B', 'FACTURA_C', 'NO_SOLICITA'
        )
    ),
    CONSTRAINT chk_pedido_entrega CHECK (medio_entrega IN ('RETIRO_LOCAL', 'ENVIO')),
    CONSTRAINT chk_pedido_localidad CHECK (
        localidad_envio IS NULL OR localidad_envio IN ('VILLA_MARIA', 'VILLA_NUEVA')
    ),
    CONSTRAINT chk_pedido_cliente_online CHECK (
        tipo_venta = 'LOCAL' OR id_cliente IS NOT NULL
    ),
    CONSTRAINT chk_pedido_datos_envio CHECK (
        (medio_entrega = 'RETIRO_LOCAL' AND localidad_envio IS NULL AND direccion_envio IS NULL)
        OR
        (medio_entrega = 'ENVIO' AND localidad_envio IS NOT NULL AND direccion_envio IS NOT NULL)
    ),
    CONSTRAINT chk_pedido_importes CHECK (
        subtotal >= 0
        AND descuento_cliente >= 0
        AND descuento_mayorista >= 0
        AND descuento_oferta >= 0
        AND total >= 0
    )
);

CREATE INDEX ix_pedidos_cliente ON pedidos(id_cliente);
CREATE INDEX ix_pedidos_fecha ON pedidos(fecha_creacion);
CREATE INDEX ix_pedidos_tipo_estado ON pedidos(tipo_venta, estado_pedido);
CREATE INDEX ix_pedidos_pago ON pedidos(estado_pago);

CREATE TABLE detalle_pedido (
    id_detalle_pedido     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido             INT NOT NULL REFERENCES pedidos(id_pedido),
    id_producto           INT NOT NULL REFERENCES productos(id_producto),
    cantidad              INT NOT NULL,
    precio_unitario       NUMERIC(12,2) NOT NULL,
    costo_unitario        NUMERIC(12,2),
    descuento_aplicado    NUMERIC(12,2) NOT NULL DEFAULT 0,
    subtotal              NUMERIC(12,2) NOT NULL,
    CONSTRAINT chk_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_detalle_precio CHECK (precio_unitario >= 0),
    CONSTRAINT chk_detalle_costo CHECK (costo_unitario IS NULL OR costo_unitario >= 0),
    CONSTRAINT chk_detalle_descuento CHECK (descuento_aplicado >= 0),
    CONSTRAINT chk_detalle_subtotal CHECK (subtotal >= 0)
);

CREATE INDEX ix_detalle_pedido_pedido ON detalle_pedido(id_pedido);
CREATE INDEX ix_detalle_pedido_producto ON detalle_pedido(id_producto);

-- ============================================================
-- STOCK
-- ============================================================

CREATE TABLE movimientos_stock (
    id_movimiento_stock    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto            INT NOT NULL REFERENCES productos(id_producto),
    id_usuario             INT NOT NULL REFERENCES usuarios(id_usuario),
    tipo_movimiento        VARCHAR(30) NOT NULL,
    origen                 VARCHAR(30) NOT NULL,
    cantidad               INT NOT NULL,
    stock_anterior         INT NOT NULL,
    stock_posterior        INT NOT NULL,
    fecha                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_movimiento_tipo CHECK (tipo_movimiento IN (
        'ENTRADA', 'SALIDA', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO',
        'DEVOLUCION', 'RESERVA', 'LIBERACION_RESERVA'
    )),
    CONSTRAINT chk_movimiento_origen CHECK (origen IN (
        'VENTA_LOCAL', 'PEDIDO_ONLINE', 'REPOSICION_STOCK',
        'AJUSTE_MANUAL', 'DEVOLUCION', 'RESERVA_PEDIDO'
    )),
    CONSTRAINT chk_movimiento_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_movimiento_stocks CHECK (stock_anterior >= 0 AND stock_posterior >= 0)
);

CREATE INDEX ix_movimientos_producto_fecha ON movimientos_stock(id_producto, fecha);
CREATE INDEX ix_movimientos_usuario ON movimientos_stock(id_usuario);

CREATE TABLE reservas_stock (
    id_reserva_stock      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_detalle_pedido     INT NOT NULL UNIQUE REFERENCES detalle_pedido(id_detalle_pedido),
    cantidad              INT NOT NULL,
    estado                VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
    fecha_reserva         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_cierre          TIMESTAMP,
    CONSTRAINT chk_reserva_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_reserva_estado CHECK (estado IN ('ACTIVA', 'LIBERADA', 'CONSUMIDA'))
);

-- ============================================================
-- GASTOS
-- ============================================================

CREATE TABLE categorias_gasto (
    id_categoria_gasto    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                VARCHAR(100) NOT NULL,
    descripcion           TEXT,
    activa                BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX ux_categorias_gasto_nombre_lower ON categorias_gasto (LOWER(nombre));

CREATE TABLE gastos (
    id_gasto              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria_gasto    INT NOT NULL REFERENCES categorias_gasto(id_categoria_gasto),
    id_usuario            INT NOT NULL REFERENCES usuarios(id_usuario),
    id_medio_pago         INT REFERENCES medios_pago(id_medio_pago),
    descripcion           TEXT NOT NULL,
    monto                 NUMERIC(12,2) NOT NULL,
    fecha                 DATE NOT NULL DEFAULT CURRENT_DATE,
    observaciones         TEXT,
    CONSTRAINT chk_gasto_monto CHECK (monto > 0)
);

CREATE INDEX ix_gastos_fecha ON gastos(fecha);
CREATE INDEX ix_gastos_categoria ON gastos(id_categoria_gasto);
CREATE INDEX ix_gastos_usuario ON gastos(id_usuario);

COMMIT;
